# bullet.py
BULLET_SPEED = 10
BULLET_LIFETIME = 50
BULLET_XSIZE = int(32 / 2)
BULLET_YSIZE = int(32 / 2)

# enemy.py
ENEMY_MOVEMENT_SPEED = 5 / 2
ENEMY_XSIZE = int(50 / 2)
ENEMY_YSIZE = int(120 / 2)

# player.py

PLAYER_MOVEMENT_SPEED = 5 / 2
PLAYER_XSIZE = int(50 / 2)
PLAYER_YSIZE = int(120 / 2)

# image_loader.py

DEFAULT_IMAGE_SIZEX = int(50 / 1)
DEFAULT_IMAGE_SIZEY = int(120 / 1)
